# Generated by Django 4.0.5 on 2022-06-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='please update your bio', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='f_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
