# Generated by Django 4.0.5 on 2022-06-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_profile_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='health',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
